# NOTE: UNDER CONSTRUCTION

name: Build and deploy project

env:
  AZURE_WEBAPP_NAME: openai-cqm-gh-actions  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.10.0'              # set this to the Python version to use
  AZURE_WEBAPP_PACKAGE_PATH: './app'
  AZURE_WEBAPP_FRONT_PATH: './app'
  STARTUP_COMMAND: ''
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install and build project
        working-directory: ${{ env.AZURE_WEBAPP_FRONT_PATH }}/frontend
        run: |
          npm install
          npm run build
      #setup Python
      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      #Install dependencies
      - name: Install dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/backend
        run: |
          python3 -m venv venv
          source venv/bin/activate \
          pip install setuptools \
          pip install -r requirements.txt \
          mkdir static \
          mv ${{ env.AZURE_WEBAPP_FRONT_PATH }}/frontend/* ${{ env.AZURE_WEBAPP_FRONT_PATH }}/backend/static/

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            !venv/
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-20.04
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/backend
            !venv/
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          startup-command: ${{ env.STARTUP_COMMAND }}
